# Generated by Django 5.1.7 on 2025-05-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financas', '0002_categoria_usuario_alter_transacao_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='frequencia',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('semanal', 'Semanal'), ('anual', 'Anual')], default='mensal', max_length=20),
        ),
        migrations.AddField(
            model_name='transacao',
            name='recorrente',
            field=models.BooleanField(default=False),
        ),
    ]
